apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ip-app
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-ip-app
  template:
    metadata:
      labels:
        app: flask-ip-app
    spec:
      containers:
        - name: flask-ip-app
          image: gbmkocc1/flask-ip-app:latest
          ports:
            - containerPort: 5000
