apiVersion: v1
kind: Service
metadata:
  name: flask-ip-service
  namespace: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-ip-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
